# Generated by Django 4.1.3 on 2022-11-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
